User.create!(email: 'admin@ifsu.com', 
						password: 'admin@ifsu', 
						password_confirmation: 'admin@ifsu', 
						first_name: 'Administrator', 
						last_name: 'User', 
						role: 'admin')
User.create!(email: 'employee@ifsu.com', 
						password: 'employee@ifsu', 
						password_confirmation: 'employee@ifsu', 
						first_name: 'Employee', 
						last_name: 'User', 
						role: 'employee')
User.create!(email: 'developer@ifsu.com', 
						password: 'developer@ifsu', 
						password_confirmation: 'developer@ifsu', 
						first_name: 'Developer', 
						last_name: 'User', 
						role: 'developer')
# Student.create!(first_name: 'Christopher', 
# 						middle_name: 'Dulnuan',
# 						last_name: 'Pumihic', 
# 						role: 'student', 
# 						gender: "male",
# 						birthdate: Date.new(1993, 7, 30),
# 						mobile: "09997867564",
# 						id_number: '131609',
# 						tag_uid: '0014934349',
# 						course_id: 1,
# 						year_level_id: 1,
# 						address_attributes: { house_number: '220',
# 																	sitio: 'Bahawit',
# 																	barangay: 'Poblacion West',
# 																	municipality: "Lagawe",
# 																	province: 'Ifugao' } )